from typing import Any, Optional

from pydantic import BaseModel, Field


class DeviceRegistration(BaseModel):
    """A device as reported by a node at registration time.

    The ESP32 knows only what hardware it has — no UI details. The `name` is
    optional: the backend picks a sensible default for real nodes; the
    simulator sends friendly names so the demo reads nicely. Users can always
    rename later without touching the id."""

    id: str
    type: str
    sensorType: Optional[str] = None
    capabilities: list[str] = Field(default_factory=list)
    name: Optional[str] = None


class NodeRegistration(BaseModel):
    node_id: str
    devices: list[DeviceRegistration]


class DeviceStateReport(BaseModel):
    """A node reporting the current state of one of its devices."""

    id: str
    state: Optional[dict[str, Any]] = None
    data: Optional[dict[str, Any]] = None
    online: Optional[bool] = None


class NodeReport(BaseModel):
    node_id: str
    devices: list[DeviceStateReport]


class RenameRequest(BaseModel):
    name: str


class CreateDeviceRequest(BaseModel):
    """A device added from the dashboard. The id is generated by the backend
    (e.g. light_02); the user supplies the name, the GPIO pin the hardware is
    wired to, and the device type."""

    name: str
    type: str
    pin: int
    sensorType: Optional[str] = None
